from autoetl import __version__ as VERSION

DEFAULT_USER_AGENT = f"autoetl/{VERSION}"
DEFAULT_TIMEOUT = 30
DEFAULT_MAX_RETRIES = 3
DEFAULT_BACKOFF_FACTOR = 1
DEFAULT_RATE_LIMIT = 10
DEFAULT_BROWSER_TYPE = "chromium"
